# Generated by Django 5.2.1 on 2025-07-13 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land_management', '0009_add_notification_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landregistration',
            name='transaction_reference',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
