# Generated by Django 5.2.1 on 2025-07-13 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land_management', '0010_alter_landregistration_transaction_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landregistration',
            name='registration_type',
            field=models.CharField(blank=True, choices=[('sale', 'Land Sale'), ('gift', 'Gift Land'), ('inheritance', 'Inheritance'), ('exchange', 'Land Exchange'), ('donation', 'Donation'), ('court_order', 'Court Order'), ('government_allocation', 'Government Allocation')], default='sale', max_length=30),
        ),
        migrations.AlterField(
            model_name='landregistration',
            name='transaction_reference',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
