# Generated by Django 5.2.1 on 2025-07-13 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('land_management', '0011_alter_landregistration_registration_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landsurvey',
            name='land_direction',
        ),
    ]
