# Generated by Django 5.2.1 on 2025-07-13 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land_management', '0012_remove_landsurvey_land_direction'),
    ]

    operations = [
        migrations.AddField(
            model_name='landsurvey',
            name='land_direction',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='landregistration',
            name='transaction_reference',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
