# Generated by Django 5.2.1 on 2025-07-13 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land_management', '0013_landsurvey_land_direction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landsurvey',
            name='parcel_number',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='landsurvey',
            name='survey_number',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
