# Generated by Django 5.2.1 on 2025-07-13 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land_management', '0014_alter_landsurvey_parcel_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='deputy_mayor_signature',
            field=models.FileField(default=1, upload_to='signatures/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='approval',
            name='director_signature',
            field=models.FileField(default=1, upload_to='signatures/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='approval',
            name='mayor_signature',
            field=models.FileField(upload_to='signatures/'),
        ),
        migrations.AlterField(
            model_name='approval',
            name='secretary_signature',
            field=models.FileField(default=3, upload_to='signatures/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='landsurvey',
            name='parcel_number',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='landsurvey',
            name='survey_number',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
