# Generated by Django 5.2.1 on 2025-07-13 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land_management', '0015_alter_approval_deputy_mayor_signature_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landregistration',
            name='land_code',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
