# Generated by Django 5.2.1 on 2025-07-13 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land_management', '0016_alter_landregistration_land_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='landregistration',
            name='land_direction_north',
            field=models.CharField(blank=True, choices=[('building', 'Building'), ('road', 'Road'), ('empty', 'Empty')], max_length=20, null=True),
        ),
    ]
